### ISSUE TITLE
Working with the docker container

### ISSUE THREAD

**Issue by Binternet** [pelias/polylines#160] opened 2018-03-28 09:19 UTC
The single planet-wide road network file is not available, but I do have a full planet osm pbf & oa on my instance at `/data/osm` and `/data/oa` - how can I work the polylines container to work with these paths and store the output polyline file to `/data/osm` and `/data/oa` respectively on the host instance?

**Comment by missinglink** [comment] 2018-03-28 12:04
This is a duplicate of your other issue, you can use the `-v` flag for `docker run` to expose local paths to the running container.

**Closed by missinglink** 2018-03-28 12:04 UTC
